### ISSUE TITLE
Support for  Marianne Pellet stove

### ISSUE THREAD

**Issue by abcklaus** [marcopal74/home-assistant-palazzetti#1]
Hi,

let me start with saying thank you for creating this integration! Great Job.

We are using a Palazzetti Marianne Pellet stove

[https://palazzetti.it/products/pellet-stoves/air/marianne-steel-moka-9-1-kw-ventilated-0-speed-fan/](url)

I have installed your integration in my Home Assistant environment. After the installation I see the following entities:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/60260208/115522242-3ac45a80-a28c-11eb-9f3a-9a8f4c82c314.png">

As far as I see two feature are missing:

- turn on/off the stove (actually there is a switch - but it doesn't work)
- turn on/off the fan (silent mode)
- set fan to automatic mode

Would be great if you could have a look into that.

Thanks

Michael

**Comment by marcopal74** [comment]
Hello Michael,
thanks for your feedback, I'll give a look into this issue this weekend.

**Comment by marcopal74** [comment]
Since I see you're having fun [coding](https://github.com/abcklaus/vihio) take a look to

**Comment by mars-cmd** [comment]
Ciao 

Ho lo stesso problema, non riesco ad accendere la mia stufa linda usando il tasto ON/OFF.

Mi potete aiutare per favore ?
