### ISSUE TITLE
Restart integration without restarting HA

### ISSUE THREAD

**Issue by carmelo42** [marcopal74/home-assistant-palazzetti#11]
Hello ! 
Just installed home-assistant-palazzetti integration on Home Assistant.
Sometimes, I have wifi issue, and the connection box lost network for a few minutes. 
But the integration does not automatically reconnect to the box and all parameters are unavailables : 

![image](https://user-images.githubusercontent.com/2070041/187629766-231ebe3e-2dd6-4629-91e1-0147caf4e77a.png)

The only solution I found is restarting whole HA system, but it's kind of annoying. Is there any solution without rebooting ?

**Comment by Sieste68** [comment]
Hi,
I also have the same issue.
ComboBox is connected but nothing is retrived from. Difficult to follow and manage the Palazzetti by this way :-(

**Comment by 5472qaywsx** [comment]
In my situation, I have to connect the connbox to the main wireless network to make the integration work; if I connect the connbox over the guest wireless network, the integration doesn't work ("ConnBox doesn't respond").
Maybe it's the same in your case? Double check over this.

**Comment by Sieste68** [comment]
Hi,

Thanks, I reset the CBox configuration on the main wifi network since a
while, but in the doubt, I did it again.
And then, I confirm that I still have the same issue, unfortunately

Patrick

Le sam. 24 déc. 2022 à 14:01, 5472qaywsx ***@***.***> a
écrit :

**Comment by marcopal74** [comment]
> In my situation, I have to connect the connbox to the main wireless network to make the integration work; if I connect the connbox over the guest wireless network, the integration doesn't work ("ConnBox doesn't respond").
> Maybe it's the same in your case? Double check over this.

### Answering just for the guest wireless network:
the reason why you don't get data (and probably also the Palazzetti Mobile App controls the stove in "out of home mode") is because guest networks usually block the traffic between the devices within the network and allow only connectivity to the Internet. In this way HA cannot reach the CBox.

**Comment by marcopal74** [comment]
### About Disconnections:
I close this issue and suggest to move to #8 . Unfortunately is still not fully solved (I really don't have so much time to dedicate to it) but there are suggestions in the comments.
I'll keep it open.
