### ISSUE TITLE
Compatibilità con ET4W

### ISSUE THREAD

**Issue by mattiabrunello5** [marcopal74/home-assistant-palazzetti#12]
Ciao è compatibile con il controllo et4W

**Comment by marcopal74** [comment]
Si, è compatibile. Fammi sapere se ci sono problemi ma lo ho testato. L'unica cosa è che vista la frequenza di polling dell'integrazione il controller dell'ET4W è un po' sovraccaricato. Comunque puoi provarla alla peggio si riavvia il controller ma non succede nulla di grave.
