### ISSUE TITLE
Integration does not work anymore with Home Assistant 2022.10

### ISSUE THREAD

**Issue by carmelo42** [marcopal74/home-assistant-palazzetti#13]
Hello,
Since the upgrade, the integration does not show some of the settings (it was perfectly working before) : 

![Capture d’écran 2022-10-08 à 11 35 36](https://user-images.githubusercontent.com/2070041/194700904-47049c6c-7d18-439c-bdf4-d596aef35560.png)

![Capture d’écran 2022-10-08 à 11 35 56](https://user-images.githubusercontent.com/2070041/194700908-82ad2862-fcef-423f-9509-5e9998c414ed.png)

**Comment by carmelo42** [comment]
Hey @hpommier thanks for your help. I tried but after HA restart the Palazzetti integration is not working : 

<img width="547" alt="Capture d’écran 2022-10-11 à 11 39 06" src="https://user-images.githubusercontent.com/2070041/195055629-5f0cdbf0-45ee-42ea-b2fc-80190348f9ab.png">

**Comment by hpommier** [comment]
Sorry wrong copy/paste, Try adding : 
`self.editable = True`

**Comment by marcopal74** [comment]
> Perfect :) It works ! 
> 
> 
> 
> @marcopal74 Can you please add the patch made by @hpommier ?

Sure! @hpommier would you like to create a PR? It's your patch ;-)

**Comment by hpommier** [comment]
@marcopal74 : done ! Thanks for your work on this integration.
