### ISSUE TITLE
How set to the language from Italian to Franch

### ISSUE THREAD

**Issue by Sieste68** [marcopal74/home-assistant-palazzetti#15]
Hi,

I didn't find the way to get all text in French. May I miss something on the configuration.
Can you provide any direction?

**Comment by carmelo42** [comment]
You can modify inside Home Assistant : 

<img width="989" alt="image" src="https://user-images.githubusercontent.com/2070041/209344924-e9785873-266f-42ba-b6fd-0e38746c486f.png">

**Comment by Sieste68** [comment]
Hi Carmelo42

Thanks but why keep translations files in the sub folder ´translation’ ? ;-)

**Comment by marcopal74** [comment]
Sorry @Sieste68 but translations are only related to some strings during the configuration process, no more.
