### ISSUE TITLE
My Climate compatibility 

### ISSUE THREAD

**Issue by smunos66** [marcopal74/home-assistant-palazzetti#17]
Thank you for this great work. I use this integration for a few days and it’s really useful !
I will add two sensors « my climate » to my stove, this integration support these thermometers ?

**Comment by marcopal74** [comment]
Theoretically yes if MyClimate is used for the main room temperature, surely not if used for a secondary room in case of Pro2 or Pro3 products. If used for the central fan (main temperature) the room temperature should be the one of the MyClimate.
