### ISSUE TITLE
Integration broken with HA

### ISSUE THREAD

**Issue by carmelo42** [marcopal74/home-assistant-palazzetti#18]
Since the 2024.2.0 update / OS 11.5 the integration does not work anymore : no more updates or control of my stove.
I found this in the logs : 

```
2024-02-08 18:58:01.351 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up palazzetti platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/palazzetti/sensor.py", line 53, in async_setup_entry
    SensorX(
  File "/config/custom_components/palazzetti/sensor.py", line 142, in __init__
    self._unique_id = "vuoto_" + self._key
                      ~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Zesstra69** [comment]
Same here, I suspect the bunch of changes talking about stricter test relater data types. I hope the owner is still around. If not, well, i'll try to understand the code at least

**Comment by Zesstra69** [comment]
I have just upgraded to 2024.2.1 and it solved the issue. I believe this one can be closed :-)

**Comment by maustru** [comment]
Me not :)

![grafik](https://github.com/marcopal74/home-assistant-palazzetti/assets/121907657/80db69da-af81-4fdc-ad19-a950c822b2cd)

after the update same Problem.
I have a Palazzetti Julie

**Comment by Zesstra69** [comment]
FYI, I have a Bianca 9. A noticeable difference between mine and yours, beyond that obvious model, is that mine reports a firmware version: "mod 620 v44 2020-12-11". No clue however if this can be of any help. Is there any Palazzetti support people reading this ?

**Comment by maustru** [comment]
Also for information:
My Connectbox has the firmware: 2.5.3 2022-11-08 15:52:19 (9e8e347)

**Comment by maustru** [comment]
Okay... Absolutely hilarious. The entities were marked as unreachable. Nevertheless, I was able to access them via NodeRed. As of noon today, all entities are fully available again.
In this case it can also be closed for me

![grafik](https://github.com/marcopal74/home-assistant-palazzetti/assets/121907657/2983afb7-263d-47de-b19a-f88dea30cf86)

**Comment by marcopal74** [comment]
Thank you all for the discussion, closing the issue. There aren't enough double check in the code so if some values are NULL the code probably fails, sorry for that. 🤷
