### ISSUE TITLE
Added compatibility with WirelessPalaControl

### ISSUE THREAD

**Issue by toutrob** [marcopal74/home-assistant-palazzetti#4]
I built the DIY box from @Domochip, but when I wanted to associate it with this component, I had a connection error with the IP address.

I don't think it's very complex to add the compatibility, since they work with the same commands.
Would you have time to look into it ?

Thank you.

[https://github.com/Domochip/WirelessPalaControl](url)

**Comment by Domochip** [comment]
Hello,

I'm currently working to get WPalaControl compatible with all different plugins that handle CBox.
Stay tune on WPalaControl repo :-)

**Comment by toutrob** [comment]
Ah, that's perfect so, thank you !

**Comment by Domochip** [comment]
Hello,

The new version has been released : https://github.com/Domochip/WirelessPalaControl/releases/tag/v1.4.1-2.0.0
You should now be able to use this HomeAssistant plugin like any CBox.
Let me know if you encounter any issue.

**Comment by toutrob** [comment]
Bonjour, merci beaucoup, je teste ça dès que j'ai du temps !
