### ISSUE TITLE
FAN - Auto mode

### ISSUE THREAD

**Issue by JiMSigneLesArbres** [marcopal74/home-assistant-palazzetti#7]
Main Fan slider is set with max value to 5, but 7 ( means auto ) is a correct value.
When I set auto on the IOS app, the slider change to 7. But how to set it to 7 with the slider ?

**Comment by marcopal74** [comment]
I'll look into it. Need to implement two more switches one for HIGH mode and one for AUTO mode (like the one for SILENT mode).
Please give me some time 😉

**Comment by marcopal74** [comment]
OK, latest commit includes Auto mode for Fan.
Not tested but should work. Let me know...

**Comment by JiMSigneLesArbres** [comment]
It works perfectly ! thank you :-)

**Comment by marcopal74** [comment]
> It works perfectly ! thank you :-)

UI doesn't update immediately but the command works. Thank you for downloading my integration.
