### ISSUE TITLE
Pellet count - Value drops issue

### ISSUE THREAD

**Issue by JiMSigneLesArbres** [marcopal74/home-assistant-palazzetti#9]
Hello,

I see Strange value drop on Pellet Consumato count.  Is there a way to prevent it ?

![2022-03-04 12_01_17-Pellet_drop](https://user-images.githubusercontent.com/76914711/156751857-623352dd-20cb-47d4-9698-86f5c91eba1f.png)

**Comment by marcopal74** [comment]
Sorry for that but I think it's a wrong read from the Board which sometimes can happen. 

I can try to check if before updating the counter field is possible to compare the new value with the existing one and if lower  I don't update.

Give me some time...

**Comment by marcopal74** [comment]
...ok, patch to palazzetti-sdk-local-api to prevent PQT to be lower than previous version has been published to PyPI v1.0.14.
Hope this works!!

I've updated the requirements for this Integration.

**Comment by JiMSigneLesArbres** [comment]
![image](https://user-images.githubusercontent.com/76914711/156928526-049a8d2e-e538-4242-afd4-d067f02485d7.jpeg)

![image](https://user-images.githubusercontent.com/76914711/156928538-ee5c09ac-de7c-4854-aaf2-74fcbedeaa5e.jpeg)

It works well again after the update. 
Thank you very much 👍🏻
